---

- name: Create LDAP Database Directory
  file:
    path=/var/lib/ldap/{{ openldap.domain_name }}/
    state=directory
    owner={{ openldap_server_user }}
    group={{ openldap_server_user }}

- name: Create LDAP Certificate Directory
  file:
    path={{ openldap.path }}/certs/
    state=directory
    owner={{ openldap_server_user }}
    group={{ openldap_server_user }}

- name: Generate SSL Private Key
  shell:
    openssl genrsa -des3 -passout pass:password -out ldap1.key 1024
    chdir={{ openldap.path }}/certs/
    creates={{ openldap.path }}/certs/ldap1.key

- name: Strip Password from SSL Private Key
  shell:
    openssl rsa -in ldap1.key -passin pass:password -out ldap.key
    chdir={{ openldap.path }}/certs/
    creates={{ openldap.path }}/certs/ldap.key

- name: Create and Sign SSL Certificate
  shell:
    openssl req -new -x509 -subj '/C={{ openldap.country }}/ST={{ openldap.state }}/L={{ openldap.location }}/O={{ openldap.organization }}/CN={{ ansible_hostname }}/' -days 3650 -key ldap.key -out ldap.crt -extensions v3_ca
    chdir={{ openldap.path }}/certs/
    creates={{ openldap.path }}/certs/ldap.crt

- name: Copy Supporting Files
  copy:
    src=ldap
    dest=/etc/sysconfig/ldap
    mode=0755
  when: openldap_server_enable_ssl and ansible_os_family == "RedHat"
  notify:
   - restart slapd

- name: Copy Supporting Files
  copy:
    src=slapd_fedora
    dest=/etc/sysconfig/slapd
    mode=0755
  when: openldap_server_enable_ssl and ansible_distribution == "Fedora"
  notify:
   - restart slapd

- name: Copy Supporting Files
  copy:
    src=slapd
    dest=/etc/default/slapd
    mode=0755
  when: openldap_server_enable_ssl and ansible_os_family == "Debian"
  notify:
   - restart slapd

- name: Copy the Base DN LDIF
  template:
    src=domain.ldif
    dest=/tmp

- name: Add Base Domain
  shell:
    ldapadd -x -D "cn=Manager,dc={{ openldap.domain_name.split('.')[0] }},dc={{ openldap.domain_name.split('.')[1] }}" -w {{ openldap.password }} -f /tmp/domain.ldif && touch {{ openldap.path }}/rootdn_created
    creates={{ openldap.path }}/rootdn_created
