---

- name: Add OS-Specific Variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Requisite Packages
  yum:
    name={{ item }}
    state=installed
  with_items: openldap_server_pkgs
  when: ansible_os_family == 'RedHat'


- name: Install Requisite Packages
  apt:
    name={{ item }}
    state=installed
    update_cache=yes
  with_items: openldap_server_pkgs
  environment: env
  when: ansible_os_family == 'Debian'

- name: Delete Configuration Directory
  file:
    path={{ openldap.path }}/slapd.d
    state=absent

- name: Generate LDAP Password
  shell:
    slappasswd -s {{ openldap.password }}
  register: root_password

- name: Copy slapd.conf
  template:
    src=slapd.conf.j2
    dest={{ openldap.path }}/slapd.conf
  when: ansible_os_family == "RedHat"
  notify:
   - restart slapd

- name: Copy slapd.conf
  template:
    src=slapd.conf_ubuntu.j2
    dest={{ openldap.path }}/slapd.conf
  when: ansible_os_family == "Debian"
  notify:
   - restart slapd

- name: Copy ldap.conf
  template:
    src=ldap.conf.j2
    dest={{ openldap.path }}/ldap.conf
